### ISSUE TITLE
[feature_idea]出力デバイス先の指定

### ISSUE THREAD

**Issue by cahlchang** [gimKondo/sound-of-cthulhu#45]
### ABOUT

出力デバイス先の指定が出来る。

### DETAIL

このソフトウェアが、出力先デバイスを指定出来るようになると、非常に使っていて楽しくなると思います！
DJソフトウェアのように出力先のデバイスを切り替える事が出来ると良いな、と思います。

シーンとしては、オンラインセッションでのキーパリング中の音声再生を想定しています。
オンラインセッションでは、その特性上音声チャットアプリを使用する事が多いです。
音声チャットアプリは、複数人の会話が聞こえやすいように最適化されています。
例えば、一定音量を下回るとそこで、そのユーザの音声を無音化したり、その人のしゃべる音声レベルから聞こえやすさの最適化を行っているので、喋るユーザと音声が流れるユーザが別になっていると音声体験が向上します。
参考リンク：この他にも
https://gigazine.net/news/20180912-webrtc-discord/

そのため、オンラインセッションでは複数アカウントを用いて「自分の喋る声」と「音声BGM」の2ラインの送信を行いますが、この時に1clientでこの処理を行うと、音声のルーティング処理が発生し、面倒な事になります。
（仮想音声デバイス・音声ルーティング・イコライザーなど）

ここで、出力デバイスを指定できれば、音声ルーティング処理が不要となるので、オンラインセッションとしてとても使いやすくなります。
現在はその場で音声を鳴らす用としての利用想定だとは思うのですが、将来のアイデアとして出力先デバイスを指定できればとても魅力なソフトウェアになると思います！

### REF

https://www.npmjs.com/package/node-core-audio
node-core-audioでは、デバイスのインターフェースは取得できそうです。

### VS

https://rekordbox.com/ja/
出力デバイスが指定出来るので、音声ルーティングが不要になります。
また、イコライザー処理などが出来るため、現在私が利用しているソフトウェアはこれになります。
ただ、OSSでは無い、ソフトウェアが重い、本格的なDJソフトウェアなので導入障壁が高い、などの問題があります。
TRPGのキーパリングとしてはリッチすぎるので、このsound-of-cthulhuでデバイスの指定ができれば、と思います。

https://www.apple.com/jp/apple-music/
iTunesあらためapple-music。
標準ソフトウェアなのに、イコライザーやオーディオデバイス変更という、キーパリングに最低限必要なものが揃っています。

考えてくれれば、嬉しいです。

**Comment by u-ishii** [comment]
とりあえず手がかり
https://github.com/WebAudio/web-audio-api-v2/issues/10

**Comment by u-ishii** [comment]
@cahlchang 
あまり知識がないのですが、仮想デバイスに出力できればいいってことですよね？
実装はおそらくできると思いますが、正しく動作しているか検証する方法とかわかりそうだったら教えていただくことはできますか？

**Comment by u-ishii** [comment]
とりあえず実装しました。
音が歪む？バグがあるらしいのですがそれはまた別の Issue で…。
https://github.com/gimKondo/sound-of-cthulhu/pull/54
