### ISSUE TITLE
CDをして、git releaseにビルド差分を上げたい

### ISSUE THREAD

**Issue by cahlchang** [gimKondo/sound-of-cthulhu#71]
**その機能は何を解決しますか？**
新しいバージョンを作るためにクロスプラットフォームビルドをしてリリースに上げる手間が省ける
featのdiscordの対応でffmpegのバイナリを入れているので、macのターゲットビルドができなくなっている可能性があるので、その対応も込み（Dockerでビルドすれば問題ないが）

**解決案**
ブランチがマスターにマージされる or リリースが切られる or タグが変わった状態でマスターマージなどのトリガーで
github actrions（など）でビルドが行われ、リリースにビルドが上げられる

**追加情報**
https://github.com/cahlchang/sound-of-cthulhu/blob/temp/upload-binary/.github/workflows/electron.yml
個人用ブランチではこのように実現しています。
機能としてOKならトリガーと命名ルールだけ変えて入れてしまおうと思います。

**Comment by gimKondo** [comment]
私の提案。

1. 開発の統合ブランチをdevに変更
2. masterにマージされたときにタグ＆リリースを作成
  - プルリクのタイトルからタグ名を取る方法がある
  - https://qiita.com/gimKondo/items/00242811e30ab5ed60d0

- その他
  - `yarn install` は `yarn install --frozen-lockfile` が良さそうです
  - linux版は需要なさそうなので消しておきましょう
